export const STAGES = {
  UNDERSTAND: 'UNDERSTAND',
  CLARIFY: 'CLARIFY',
  ROOT_CONCERN: 'ROOT_CONCERN',
  TEACHING: 'TEACHING',
  REFLECT: 'REFLECT',
  ACTION: 'ACTION',
  REVIEW: 'REVIEW',
};

export const STAGE_ORDER = [
  STAGES.UNDERSTAND,
  STAGES.CLARIFY,
  STAGES.ROOT_CONCERN,
  STAGES.TEACHING,
  STAGES.REFLECT,
  STAGES.ACTION,
  STAGES.REVIEW,
];

export const MODES = {
  CLARIFY: 'CLARIFY',
  REFLECT: 'REFLECT',
  TEACHING: 'TEACHING',
  ACTION: 'ACTION',
  REVIEW: 'REVIEW',
  NO_SOURCE: 'NO_SOURCE',
  HUMAN_SUPPORT: 'HUMAN_SUPPORT',
};

export const TOPICS = [
  'FAILURE',
  'FEAR',
  'ANGER',
  'PURPOSE',
  'RELATIONSHIPS',
  'WORK',
  'GRIEF',
  'GENERAL',
];

export const ACTION_STATUSES = [
  'PENDING',
  'COMPLETED',
  'PARTIALLY_COMPLETED',
  'ABANDONED',
  'IN_PROGRESS',
];
